name: Extract Changelog
description: Extracts a version from the changelog
branding:
  icon: book-open
  color: white
inputs:
  version:
    description: The version to extract
    required: true
  version-marker-type:
    description: The markdown element to look for versions
    required: false
    default: heading
  version-marker-depth:
    description: The depth of the markdown element to look for versions
    required: false
    default: 2
  changelog:
    description: The changelog body. 
      If not provided, the `changelog-file` will be used
    required: false
  changelog-file:
    description: The changelog file
    required: false
    default: CHANGELOG.md
outputs:
  body:
    description: Extracted changelog body for the specified version
runs:
  using: node20
  main: dist/index.js
